config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :users
  resources :users, only:[:index,:show]
  
  get 'inquiries/index' => 'inquiry#index'

  post 'inquiries/confirm' => 'inquiry#confirm'

  post 'inquiries/thanx' => 'inquiry#thanx'

  get 'top/index'

  resources :blogs

   root 'top#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  validates :name, presence:{ message: "名前を入力してください"}
  validates :content, presence:{ message: "内容を入力してください"}
  
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable # confirmable
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
before_filter :authenticate_user!
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content,:user_id)
    end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    @inquiry = Inquiry.new
  end

  def confirm
    @inquiry = Inquiry.new(params_create)
     if @inquiry.valid?
#      
     else
#        redirect_to inquiries_index_path
       render action: 'index'
    end
   
  def thanx
    @inquiry = Inquiry.create(params_create)
  end
  end
  
    private
    
    def params_create
      params.require(:inquiry).permit(:name,:content)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<%= f.hidden_field :user_id,:value => current_user.id %>

<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>記事</h1>

<form class="form-horizontal">
  <div class="form-group form-group-lg">
    <label class="col-sm-2 control-label" for="formGroupInputLarge">Large label</label>
    <div class="col-sm-10">
      <input class="form-control" type="text" id="formGroupInputLarge" placeholder="Large input">
    </div>
  </div>
</form>



<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= blog.user.name %></td>
        <td><%= link_to 'Show', blog %></td>
        <% if current_user.id == blog.user_id %>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <% else %>
        <% end %>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/inquiry/confirm.html.erb
<h1>確認</h1>
<%= form_for (@inquiry),url:inquiries_thanx_path do |f| %>
<%= f.hidden_field :name %>
<%= @inquiry.name %>
<%= f.hidden_field :content %>
<%= @inquiry.content %>
<%= f.submit "本当に送ってもいいですか？" %>
<% end %>

 <% if @inquiry.errors.any? %>
<div id="error_explanation" class="alert-danger">
  
  <button class="btn btn-primary" type="button">
  Messages <span class="badge"><%= @inquiry.errors.count %>件のエラー</span>
  
  
      <h2></h2>

      <ul>
        <!-- ここでeachメソッドを用いて、エラーメッセージを表示させてください。 -->
       <%  @inquiry.errors.full_messages.each do |message| %>
       <li class="errors">
        <p class="text-left"> <%= message %></p> 
         
         <% end %>
         <% end %>

app/views/inquiry/index.html.erb
<h1>問い合わせ<h1>
  
 
  
  
         <%= form_for (@inquiry),url:inquiries_confirm_path do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :content %>
         <%= f.submit "確認"  %>
  <% end %>

app/views/inquiry/thanx.html.erb
<h1>Inquiry#thanx</h1>
<p>Find me in app/views/inquiry/thanx.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pepsi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="page-header">
  <h1>はちみつ＆じんじゃー <small>ビタミンC レモン５０個分</small></h1>
</div>

  
  
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
  
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= link_to"俺のサイト",root_path %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">link</a></li>
        
     
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">
         <% if user_signed_in? %>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to"blog",blogs_path %></li>
            <li><%= link_to"ユーザ一覧",users_path %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
          
          
          
              <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <% end %>
          </a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  
  
<%= yield %>
<%= link_to "ホーム",root_path %>
</body>
</html>

app/views/top/index.html.erb
<p>テストサイト</p>

<% if user_signed_in? %>
<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
<%= link_to"中塚さんはここをおして",new_blog_path %>
<% else %>
<li><%= link_to "Login", new_user_session_path %></li>
<% end %>
<%= link_to "問い合わせ",inquiries_index_path %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% @users.each do |user| %>

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="..." alt="...">
      <div class="caption">
        <h3><%= user.name %></h3>
        <p><%= user.profile %></p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
</div>


<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>